DROP TABLE IF EXISTS "public"."candidate_info";
CREATE TABLE "public"."candidate_info" (
  "id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "candidate" varchar(32) COLLATE "pg_catalog"."default",
  "score" numeric(10,2),
  "skill" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."candidate_info"."candidate" IS '人名';
COMMENT ON COLUMN "public"."candidate_info"."score" IS '分数';
COMMENT ON COLUMN "public"."candidate_info"."skill" IS '技能';

-- ----------------------------
-- Records of candidate_info
-- ----------------------------
INSERT INTO "public"."candidate_info" VALUES ('1', 'zjwxn', 94.30, 'database');
INSERT INTO "public"."candidate_info" VALUES ('4', 'torvz', 87.30, 'database');
INSERT INTO "public"."candidate_info" VALUES ('5', 'pgbwn', 86.42, 'database');
INSERT INTO "public"."candidate_info" VALUES ('6', 'zpymj', 86.33, 'database');
INSERT INTO "public"."candidate_info" VALUES ('7', 'aoqdc', 85.97, 'database');
INSERT INTO "public"."candidate_info" VALUES ('8', 'rikqa', 84.35, 'database');
INSERT INTO "public"."candidate_info" VALUES ('9', 'ndjzg', 83.84, 'database');
INSERT INTO "public"."candidate_info" VALUES ('10', 'sbkry', 83.04, 'database');
INSERT INTO "public"."candidate_info" VALUES ('11', 'rsmgx', 82.86, 'database');
INSERT INTO "public"."candidate_info" VALUES ('12', 'yrqve', 82.28, 'database');
INSERT INTO "public"."candidate_info" VALUES ('13', 'ohbsa', 81.67, 'database');
INSERT INTO "public"."candidate_info" VALUES ('14', 'deocw', 68.59, 'database');
INSERT INTO "public"."candidate_info" VALUES ('15', 'yrmfn', 51.91, 'database');
INSERT INTO "public"."candidate_info" VALUES ('16', 'safje', 51.91, 'database');
INSERT INTO "public"."candidate_info" VALUES ('17', 'btowf', 78.64, 'database');
INSERT INTO "public"."candidate_info" VALUES ('18', 'mrogz', 77.27, 'database');
INSERT INTO "public"."candidate_info" VALUES ('19', 'bdwtg', 75.87, 'database');
INSERT INTO "public"."candidate_info" VALUES ('20', 'emohq', 75.60, 'database');
INSERT INTO "public"."candidate_info" VALUES ('21', 'mxeju', 75.10, 'database');
INSERT INTO "public"."candidate_info" VALUES ('22', 'ynhdw', 72.19, 'database');
INSERT INTO "public"."candidate_info" VALUES ('24', 'vobzy', 89.57, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('25', 'desaq', 89.18, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('26', 'wisot', 87.76, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('27', 'cktil', 87.72, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('28', 'qmdou', 87.55, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('29', 'oglmy', 87.18, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('30', 'puglm', 86.78, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('31', 'pgbjk', 86.78, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('32', 'gpdzb', 86.27, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('33', 'gjtxo', 85.64, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('34', 'csvok', 85.15, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('35', 'hnwvg', 84.88, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('36', 'utcvw', 84.36, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('37', 'drnou', 83.72, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('38', 'sxkwq', 83.60, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('39', 'gapwu', 83.34, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('40', 'soxrw', 82.52, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('41', 'shguv', 82.43, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('42', 'nkaqh', 81.93, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('43', 'frltm', 81.85, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('44', 'bxmch', 81.64, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('45', 'arufp', 81.03, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('46', 'rgmtv', 80.83, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('47', 'ihfad', 80.76, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('48', 'btnfx', 80.19, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('49', 'qvzio', 79.78, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('50', 'etrox', 79.41, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('51', 'sckmh', 79.22, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('52', 'rlqkf', 78.42, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('53', 'bfxmc', 78.25, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('54', 'ibzuw', 77.89, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('55', 'bovzh', 77.61, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('56', 'blriw', 77.61, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('57', 'oyenh', 77.19, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('58', 'ndsrt', 76.82, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('59', 'jaovs', 76.52, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('60', 'zdrng', 76.49, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('61', 'bxfyv', 76.36, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('62', 'dlukr', 75.55, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('63', 'iecbj', 75.38, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('64', 'afgyj', 75.37, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('65', 'nlcot', 75.24, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('66', 'xngcp', 74.48, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('67', 'ixnod', 73.83, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('68', 'gevtf', 73.77, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('69', 'uvgok', 73.74, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('70', 'xnriv', 73.32, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('71', 'zqxdw', 71.42, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('72', 'yfrmd', 71.28, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('73', 'luksx', 67.55, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('74', 'jwmvb', 50.40, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('76', 'hizmy', 90.21, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('77', 'wiyhc', 86.82, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('78', 'dfawu', 85.91, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('79', 'jetks', 85.12, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('80', 'jkhxy', 85.12, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('81', 'lfhpx', 84.82, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('82', 'ampry', 83.86, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('83', 'phrab', 83.44, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('84', 'evutf', 82.12, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('85', 'qovmk', 81.46, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('86', 'tmfup', 81.46, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('87', 'uliwz', 81.43, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('88', 'pyzwm', 81.41, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('89', 'ngjeh', 80.49, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('90', 'zlpcb', 80.21, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('91', 'knupo', 79.99, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('92', 'lywfg', 79.29, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('93', 'ipruy', 77.57, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('94', 'vbwro', 76.84, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('95', 'fcvxt', 75.29, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('96', 'cuzaf', 75.28, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('97', 'hejdf', 75.14, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('98', 'zqiwd', 74.39, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('99', 'otimp', 67.26, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('100', 'oczqy', 66.92, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('101', 'xjbdg', 63.34, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('102', 'kujhb', 53.19, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('103', 'tukdr', 53.19, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('104', 'zvpse', 92.30, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('105', 'adkqr', 92.27, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('106', 'hxoib', 92.26, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('107', 'iwqsc', 92.25, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('108', 'yndop', 92.24, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('109', 'vzjkx', 92.24, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('110', 'eagwv', 92.23, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('111', 'uwybm', 92.20, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('112', 'jmipd', 92.18, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('113', 'avxyi', 92.18, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('114', 'pzhst', 92.15, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('115', 'brlhm', 92.12, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('116', 'qltbe', 92.11, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('117', 'qygfj', 92.09, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('118', 'dmwyx', 92.08, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('119', 'txyuz', 92.07, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('120', 'hjyiz', 92.03, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('121', 'drgmk', 92.02, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('122', 'dkxlj', 91.99, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('123', 'gyekq', 91.99, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('124', 'fspqz', 91.98, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('125', 'bmrep', 91.97, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('126', 'dlwoa', 91.96, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('127', 'gqsuo', 91.92, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('128', 'uojzw', 91.91, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('129', 'mqzxk', 91.90, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('130', 'oxtnm', 91.86, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('131', 'vkbmq', 91.84, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('132', 'kbsda', 91.84, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('133', 'heuza', 91.82, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('134', 'jqwpy', 91.77, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('135', 'esyib', 91.75, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('136', 'rylck', 91.74, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('137', 'oqhwg', 91.66, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('138', 'frdec', 91.65, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('139', 'vsipl', 91.61, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('3', 'erqpk', 87.89, 'database');
INSERT INTO "public"."candidate_info" VALUES ('23', 'zjwxn', 100.00, 'backend');
INSERT INTO "public"."candidate_info" VALUES ('75', 'zjwxn', 90.50, 'frontend');
INSERT INTO "public"."candidate_info" VALUES ('140', 'rceai', 91.52, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('141', 'jplfa', 91.51, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('142', 'bcmfx', 91.51, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('143', 'sxebq', 91.49, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('144', 'bkuqr', 91.43, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('145', 'pgfov', 91.41, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('146', 'rsvpb', 91.41, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('147', 'ngjah', 91.39, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('148', 'qrhca', 91.38, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('149', 'aqtfv', 91.37, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('150', 'ksxun', 91.35, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('151', 'cnlmy', 91.35, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('152', 'zwybt', 91.34, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('153', 'dekbx', 91.33, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('154', 'idokj', 91.31, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('155', 'oqabs', 91.31, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('156', 'bnygv', 91.27, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('157', 'pymvw', 91.24, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('158', 'xgvtq', 91.22, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('159', 'uqadz', 91.21, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('160', 'fucya', 91.20, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('161', 'fldov', 91.17, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('162', 'bwhtr', 91.17, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('163', 'cdgze', 91.17, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('164', 'odypv', 91.15, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('165', 'ilurv', 91.13, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('166', 'cojpm', 91.13, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('167', 'lxwsa', 91.10, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('168', 'adxuq', 91.06, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('169', 'crnxa', 91.06, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('170', 'zjsgk', 91.05, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('171', 'dmnpo', 91.05, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('172', 'vnhlb', 91.03, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('173', 'grecs', 91.00, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('174', 'gumlc', 90.99, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('175', 'bocmh', 90.98, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('176', 'zklwo', 90.96, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('177', 'zjyim', 90.95, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('178', 'wnuac', 90.92, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('179', 'artuo', 90.91, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('180', 'ievas', 90.90, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('181', 'ljxde', 90.90, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('182', 'isbtx', 90.89, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('183', 'uplqn', 90.87, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('184', 'oadck', 90.86, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('185', 'wjdnf', 90.85, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('186', 'rqjxo', 90.85, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('187', 'rqfgd', 90.83, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('188', 'upfbj', 90.83, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('189', 'vybfh', 90.83, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('190', 'alxie', 90.81, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('191', 'twclz', 90.80, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('192', 'fcens', 90.77, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('193', 'upfgh', 90.75, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('194', 'kzaur', 90.73, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('195', 'ydcbj', 90.72, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('196', 'nwrpm', 90.71, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('197', 'nfvmt', 90.70, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('198', 'vpadg', 90.69, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('199', 'akqgs', 90.67, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('200', 'uhzyl', 90.67, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('201', 'ibyez', 90.67, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('202', 'tawik', 90.64, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('203', 'jwxnu', 90.61, 'smart contracts');
INSERT INTO "public"."candidate_info" VALUES ('204', 'eynsq', 91.26, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('205', 'drikp', 91.12, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('206', 'cuvwi', 88.56, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('207', 'odgfa', 90.00, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('208', 'ndgor', 89.64, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('209', 'tljdp', 89.45, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('210', 'kdtur', 89.38, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('211', 'osrme', 89.35, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('212', 'jrubw', 89.26, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('213', 'nqzgj', 89.10, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('214', 'bleqg', 89.03, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('215', 'kngxh', 89.03, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('216', 'xwbzq', 88.99, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('217', 'eymov', 88.98, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('218', 'fjyep', 88.93, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('219', 'npeuw', 88.92, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('220', 'huydp', 88.84, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('221', 'pinyr', 88.80, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('222', 'nswig', 88.73, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('223', 'tyxns', 88.73, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('224', 'irydm', 88.71, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('225', 'aniwf', 88.71, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('226', 'jlczi', 88.65, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('227', 'schmf', 88.57, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('228', 'wrnmv', 88.45, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('229', 'tipzj', 88.43, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('230', 'gbwfl', 88.17, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('231', 'tgwvz', 86.12, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('232', 'jlukw', 85.18, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('233', 'dhoua', 85.17, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('234', 'wxhen', 84.44, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('235', 'okbis', 83.26, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('236', 'mpzgl', 83.15, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('237', 'txqnk', 80.95, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('238', 'olpjv', 79.55, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('239', 'nwxrf', 79.01, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('240', 'gbfzx', 75.79, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('241', 'nuozi', 72.72, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('242', 'wvlgb', 67.75, 'solidity');
INSERT INTO "public"."candidate_info" VALUES ('243', 'hupnd', 89.08, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('244', 'lsxgq', 88.24, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('245', 'zqwnh', 88.03, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('246', 'xsakd', 86.47, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('247', 'juote', 84.82, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('248', 'psmwh', 83.35, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('249', 'vocfy', 83.04, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('250', 'bcsjx', 78.50, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('251', 'fvnhp', 76.78, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('252', 'kvobr', 75.21, 'cryptocurrency');
INSERT INTO "public"."candidate_info" VALUES ('253', 'frdjp', 87.73, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('254', 'qbtvc', 87.25, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('255', 'hatce', 86.76, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('256', 'vfkqi', 85.63, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('257', 'ogjui', 85.18, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('258', 'byqnw', 83.18, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('259', 'pkfaw', 81.40, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('260', 'lkqoc', 80.77, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('261', 'trexb', 79.56, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('262', 'zitol', 77.79, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('263', 'kgxpq', 75.15, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('264', 'vbgmy', 74.79, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('265', 'alzog', 73.64, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('266', 'cigut', 67.99, 'bitcoin');
INSERT INTO "public"."candidate_info" VALUES ('267', 'nsxym', 90.93, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('268', 'icmrb', 90.72, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('269', 'bcnok', 90.32, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('270', 'jfznp', 90.25, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('271', 'jirky', 89.74, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('272', 'aoqwj', 88.30, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('273', 'hqeod', 89.71, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('274', 'ykmzj', 89.64, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('275', 'wrfds', 89.15, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('276', 'jxcrg', 88.87, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('277', 'qoduk', 88.79, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('278', 'yuhvz', 88.60, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('279', 'ytsfz', 88.55, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('280', 'hdzej', 88.47, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('281', 'nocvi', 88.44, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('282', 'cbtqe', 88.42, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('283', 'yzjir', 88.32, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('284', 'hfnqa', 88.29, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('285', 'lcoub', 88.27, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('286', 'crybe', 88.17, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('287', 'xkzjv', 88.15, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('288', 'bemps', 88.05, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('289', 'edyws', 88.04, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('290', 'jhqwb', 88.04, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('291', 'mybov', 87.99, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('292', 'njrwa', 87.91, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('293', 'xdjpo', 87.91, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('294', 'enskm', 87.71, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('295', 'mxwea', 87.69, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('296', 'xicen', 87.60, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('297', 'umfwk', 87.49, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('298', 'ymgwv', 87.43, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('299', 'okldt', 87.42, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('300', 'gqbfn', 87.28, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('301', 'xvtmw', 87.25, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('302', 'zugky', 87.21, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('303', 'ziawm', 87.11, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('304', 'txgqe', 86.58, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('305', 'qkerw', 85.99, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('306', 'grven', 85.76, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('307', 'nkapr', 84.06, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('308', 'fsthg', 84.05, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('309', 'jytba', 83.58, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('310', 'nritf', 83.27, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('311', 'iyewq', 83.16, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('312', 'vtjsf', 83.14, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('313', 'lokzg', 83.08, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('314', 'byomd', 82.99, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('315', 'wutme', 82.93, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('316', 'korhe', 82.71, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('317', 'vntel', 82.27, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('318', 'fmvku', 81.35, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('319', 'dlqob', 80.85, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('320', 'viotw', 80.34, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('321', 'kvzht', 79.30, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('322', 'eotpn', 75.89, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('323', 'cuawv', 74.30, 'ethereum');
INSERT INTO "public"."candidate_info" VALUES ('324', 'nbdvq', 100.00, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('325', 'zpsnl', 95.51, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('326', 'waizg', 94.84, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('327', 'gaimd', 92.89, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('328', 'vfsko', 91.03, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('329', 'ohfpj', 83.60, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('330', 'hznre', 80.23, 'hyperledger');
INSERT INTO "public"."candidate_info" VALUES ('2', 'zjwxn1', 88.87, 'database');

-- ----------------------------
-- Primary Key structure for table candidate_info
-- ----------------------------
ALTER TABLE "public"."candidate_info" ADD CONSTRAINT "candidate_info_pkey" PRIMARY KEY ("id");
